Repository jtcressy-home/edgenode, pull requests merged in 2023-04, with the labels that each got.

#3 feat: cloud provider support
  Dockerfile.image
  overlay/files/etc/systemd/system/getty@ttyAMA0.service.d/override.conf
  overlay/files/system/oem/00_datasources.yaml
  overlay/files/system/oem/05_network.yaml
  overlay/files/usr/bin/microk8s-tailscale-apiserver-ip
  overlay/files/usr/bin/microk8s-tailscale-init
  overlay/files/usr/bin/set-hostname.py
  overlay/files/usr/bin/tailscale-logind
  overlay/files/usr/lib/systemd/system/microk8s-tailscale-apiserver-ip.service
Labels: ci-boost

#5 fix: support reading authkey from non-ro location
  overlay/files/usr/bin/tailscale-logind
Labels: ci-boost

#9 fix: trim the product_serial for the hostname
  overlay/files/system/oem/00_datasources.yaml
Labels: ci-boost

#10 fix: restart microk8s upon updating apiserver advertise address
  overlay/files/usr/bin/microk8s-tailscale-apiserver-ip
Labels: ci-boost

#11 feat: install gvnic driver
  Dockerfile.image
  overlay/files/etc/cos/bootargs.cfg
  overlay/files/etc/elemental/config.yaml
  overlay/files/etc/systemd/system/getty@ttyS0.service.d/override.conf
  overlay/files/system/oem/00_datasources.yaml
  overlay/files/system/oem/00_rootfs.yaml
Labels: ci-boost

#16 chore: fix release drafter config to enable auto-labeler
  .github/workflows/release-drafter.yml
Labels: bug

#17 fix: check for 2xx when fetching gcp metadata in case we aren't in gcp and the metadata hostname resolves anyway
  overlay/files/system/oem/00_datasources.yaml
Labels: bug, ci-boost

#20 fix: prevent microk8s from installing/launching when in livecd mode
  overlay/files/system/oem/21_ensure_microk8s.yaml
Labels: bug, build iso, ci-boost

#22 fix(ci): publish combined multi-arch tags in addition to separate arch tags
  .github/workflows/edgenode-image.yml
Labels: bug, ci-boost

#21 feat: use upstream recovery/cos to have a working, stable recovery partition
  overlay/files/etc/elemental/config.d/upgrade_channel.yaml
  overlay/files/etc/elemental/config.yaml
  overlay/files/etc/luet/luet.yaml
Labels: enhancement, build iso, ci-boost

#26 Fix dockerfile regex
  renovate.json
Labels: bug
